---
title: "Shiny App"
author: "Jiaxi Fang"
date: '2022-10-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
install.packages("tigris")
install.packages("anytime")
install.packages("plotly")

library(shiny)
library(dplyr)
library(lubridate)
library(tigris)
library(anytime)
library(plotly)
library(readr)
library(ggmap)
library(latticeExtra)
library(stringr)
library(DT)


```

```{r}
linknyc_loc <- read.csv("/Users/jiaxifang/Desktop/Applied Data Science/fall2022-project2-group11-fu-1/data/cleaned_location.csv")
linknyc_usage <- read.csv("/Users/jiaxifang/Desktop/Applied Data Science/fall2022-project2-group11-fu-1/data/cleaned_usage.csv")
```




# Data Wrangling - LinkNYC Loc
```{r}
linknyc_loc <- linknyc_loc %>%
  rename(
     'installation_date' = `Install_date`,
  )

linknyc_loc_modif <- linknyc_loc %>% 
    mutate(year = year(installation_date), 
            month = month(installation_date), 
            day = day(installation_date))

linknyc_loc_modif <- linknyc_loc_modif %>%
  mutate(num_of_years_active = 2022 - year)




linknyc_loc_5y <- linknyc_loc_modif %>% 
  filter(num_of_years_active == c('0', '1', '3', '4', '5')) # when we did <= '5', 46 and 50 is included

linknyc_loc_manhattan <- linknyc_loc_5y %>%
            filter(Borough == 'Manhattan')%>%
  rename("installation_date_Manhattan"="installation_date")


linknyc_loc_queens <- linknyc_loc_5y %>%
            filter(Borough == 'Queens')%>%
  rename("installation_date_Queen"="installation_date")


head(linknyc_loc_manhattan)
head(linknyc_loc_queens)

unique(linknyc_loc_5y$num_of_years_active)


# df for Usage
linknyc_usage_count <- linknyc_loc_5y %>%
      group_by(installation_date) %>%
      mutate(count=n())

linknyc_usage_count
```

# Data Wrangling - LinkNYC Usage
```{r}
linknyc_usage$Week <- str_remove(linknyc_usage$Week, "Week of")

linknyc_usage$Week <- anydate(linknyc_usage$Week)
```


# Shiny app development

## UI development
```{r}
ui <- navbarPage(
  
  # page name
  "LinkNYC",
                 
  # set theme
  theme = bslib::bs_theme(bootswatch = "sandstone"),    
  
  # Dashboard Background tab
  tabPanel("About",
    verbatimTextOutput("summary")
  ),
                 
  # Usage tab               
 tabPanel("Usage Trends",
       h4("Usage trends over the years"),
       sidebarLayout(sidebarPanel(selectInput("Borough","Select the borough",
                       c("Bronx","Brooklyn","Manhattan","Queens","Staten Island","all"))),
                                   
                     mainPanel(plotlyOutput("plot3"))),

        br(),
        h4("Usage Summary"),
        DT::dataTableOutput("table")

  ),
  
  # Manhattan Plot
 tabPanel("Manhattan Installation",
      em("kiosks installed across Manhattan"),
      sidebarLayout(sidebarPanel(sliderInput("installation_date_Manhattan", "Installation Date",
                                             min=as.Date("2017-01-10","%Y-%m-%d"),
                                             max= as.Date("2018-08-10","%Y-%m-%d"),
                                             value=as.Date("2017-01-15"),
                                             timeFormat="%Y-%m-%d")),
                    plotlyOutput("plot1"))),
    
   # Queens plot
  tabPanel("Queens Installation",
      em("kiosks installed across Queens"),
      sidebarLayout(sidebarPanel(sliderInput("installation_date_Queen", "Installation Date",
                                             min=as.Date("2017-02-10","%Y-%m-%d"),
                                             max= as.Date("2018-05-30","%Y-%m-%d"),
                                             value=as.Date("2017-02-15"),
                                             timeFormat="%Y-%m-%d")),
                    plotlyOutput("plot2")))

)

```

## Server development
```{r}
server <- function(input, output, session) {

# google maps API
register_google(key = "AIzaSyBYwjKlElJhVwDMQWmE7DwD0_lMvABW3hQ", write = TRUE)

# NYC map
nyc_map <- get_map(location = c(lon = -73.91, lat = 40.80), maptype = "terrain", color = 'bw', zoom = 11)

# side bar controller

# Plot: Kiosks Location Manhattan
output$plot1 <- renderPlotly({
  linknyc_loc_manhattan_New<-linknyc_loc_manhattan%>%
    filter(installation_date_Manhattan>=input$installation_date_Manhattan)
  ggplotly({
        ggmap(nyc_map) + 
          geom_point(data = linknyc_loc_manhattan_New, aes(x = Longitude, y = Latitude, 
                         color = num_of_years_active), 
                          size = 0.2, alpha = .7) +
                          scale_colour_gradient(high="red",low='green')
        }, res = 96)
  })

# Plot: Kiosks Location Queens
output$plot2 <- renderPlotly({
  linknyc_loc_queens_New<-linknyc_loc_queens%>%
    filter(installation_date_Queen>=input$installation_date_Queen)
  ggplotly({
        ggmap(nyc_map) + 
          geom_point(data = linknyc_loc_queens_New, aes(x = Longitude, y = Latitude, 
                         color = num_of_years_active), 
                          size = 0.2, alpha = .7) +
                          scale_colour_gradient(high="red",low='green') 
        }, res = 96)
  })


# Plot: number of usage over the years

output$plot3 <- renderPlotly({
  if(input$Borough=="Bronx"){
    data=subset(linknyc_usage_count,Borough=="Bronx")
  }
  
  if(input$Borough=="Brooklyn"){
    data=subset(linknyc_usage_count,Borough=="Brooklyn")
  }
  
  
   if(input$Borough=="Manhattan"){
    data=subset(linknyc_usage_count,Borough=="Manhattan")
  }

   if(input$Borough=="Queens"){
    data=subset(linknyc_usage_count,Borough=="Queens")
  }
  
   if(input$Borough=="Staten Island"){
    data=subset(linknyc_usage_count,Borough=="Staten Island")
  }
  
   if(input$Borough=="all"){
    data=linknyc_usage_count
  }
  ggplotly({
     data %>%
      ggplot(aes(x = mday(installation_date), y = count, group = Borough, color = Borough)) +
        geom_line() + labs(x="Time", y="Installation Count")
              }, res = 50)
  })

# Table
output$table <- DT::renderDataTable({
    DT::datatable(linknyc_usage)
  })

}

head(linknyc_usage_count)
```

# execute Shiny
```{r}
shinyApp(ui, server)
```
```