---
title: "Shiny App"
author: "Ferra Suryani"
date: '2022-10-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(shiny)
library(dplyr)
library(lubridate)
library(tigris)
library(anytime)
library(plotly)
library(readr)
library(ggmap)
library(latticeExtra)
library(stringr)
library(DT)

install.packages("tigris")
install.packages("anytime")
install.packages("plotly")

linknyc_loc <- read_csv("/Users/ferratan/Documents/GitHub/fall2022-project2-group11/data/LinkNYC_Locations.csv")\
linknyc_usage <- read_csv("/Users/ferratan/Documents/GitHub/fall2022-project2-group11/data/LinkNYC_Usage_Statistics_Historical_Data.csv")

```

# Data Wrangling - LinkNYC Loc
```{r}
linknyc_loc <- linknyc_loc %>%
  rename(
     'installation_date' = `Link Installation (A)`,
  )

linknyc_loc <- linknyc_loc %>%
  rename(
     'neighborhood' = `Neighborhood Tabulation Area (NTA)`
  )
     
linknyc_loc$installation_date <- anydate(linknyc_loc$installation_date)
linknyc_loc$installation_date = as.Date(linknyc_loc$installation_date)



linknyc_loc_modif <- linknyc_loc %>% 
    mutate(year = year(installation_date), 
            month = month(installation_date), 
            day = day(installation_date))

linknyc_loc_modif <- linknyc_loc_modif %>%
  mutate(num_of_years_active = 2022 - year)

linknyc_loc_modif <- linknyc_loc_modif %>%
  rename(
     'neighborhood' = `Neighborhood Tabulation Area (NTA)`
  )


linknyc_loc_5y <- linknyc_loc_modif %>% 
  filter(num_of_years_active == c('0', '1', '3', '4', '5')) # when we did <= '5', 46 and 50 is included

linknyc_loc_manhattan <- linknyc_loc_5y %>%
            filter(Borough == 'Manhattan')

linknyc_loc_queens <- linknyc_loc_5y %>%
            filter(Borough == 'Queens')

head(linknyc_loc_manhattan)
head(linknyc_loc_queens)

unique(linknyc_loc_5y$num_of_years_active)


# df for Usage
linknyc_usage_count <- linknyc_loc_5y %>%
      group_by(installation_date) %>%
      mutate(count=n())

linknyc_usage_count
```

# Data Wrangling - LinkNYC Usage
```{r}
linknyc_usage$Week <- str_remove(linknyc_usage$Week, "Week of")

linknyc_usage$Week <- anydate(linknyc_usage$Week)
```


# Shiny app development

## UI development
```{r}
ui <- navbarPage(
  
  # page name
  "LinkNYC",
                 
  # set theme
  theme = bslib::bs_theme(bootswatch = "sandstone"),    
  
  # Dashboard Background tab
  tabPanel("About",
    verbatimTextOutput("summary")
  ),
                 
  # Usage tab               
  tabPanel("Usage Trends",
       h4("Usage trends over the years"),
    # sidebarLayout(
    #   
    #   sidebarPanel(
    #     selectInput(inputId = "borough_select", label = "Borough",
    #                 choices = linknyc_usage_count$Borough)
    #         ),
    # 
    #   mainPanel(
        plotlyOutput("plot3"), br(),
        h4("Usage Summary"),
        DT::dataTableOutput("table")
      # )
    # )
  ),
  
  # Locations tab
  navbarMenu("Locations",
    
    # Manhattan plot              
    tabPanel("Manhattan",
      em("kiosks installed across Manhattan"),
      plotlyOutput("plot1")
    ),
    
    # Queens plot
    tabPanel("Queens",
      em("kiosks installed across Queens"),
      plotlyOutput("plot2")
    )
  )
)

```

## Server development
```{r}
server <- function(input, output, session) {

# google maps API
register_google(key = "AIzaSyBYwjKlElJhVwDMQWmE7DwD0_lMvABW3hQ", write = TRUE)

# NYC map
nyc_map <- get_map(location = c(lon = -73.91, lat = 40.80), maptype = "terrain", color = 'bw', zoom = 11)

# side bar controller

# Plot: Kiosks Location Manhattan
output$plot1 <- renderPlotly({
  ggplotly({
        ggmap(nyc_map) + 
          geom_point(data = linknyc_loc_manhattan, aes(x = Longitude, y = Latitude, 
                         color = num_of_years_active), 
                          size = 0.2, alpha = .7) +
                          scale_colour_gradient(high="red",low='green')
        }, res = 96)
  })

# Plot: Kiosks Location Queens
output$plot2 <- renderPlotly({
  ggplotly({
        ggmap(nyc_map) + 
          geom_point(data = linknyc_loc_queens, aes(x = Longitude, y = Latitude, 
                         color = num_of_years_active), 
                          size = 0.2, alpha = .7) +
                          scale_colour_gradient(high="red",low='green')
        }, res = 96)
  })

# Plot: number of usage over the years
output$plot3 <- renderPlotly({
  ggplotly({
     linknyc_usage_count %>%
      ggplot(aes(x = installation_date, y = count, group = Borough, color = Borough)) +
        geom_line()
              }, res = 96)
  })

# Table
output$table <- DT::renderDataTable({
    DT::datatable(linknyc_usage)
  })

}

head(linknyc_usage_count)
```

# execute Shiny
```{r}
shinyApp(ui, server)
```
```